### 3.2.1 3 yield *

yield可以对迭代器使用，称为yield委托

```js
function *test () {
	yield *[1, 2, 3]
}

for (let a of test()) {
	console.log(a)
}
```



### 3.2.3提前完成

生成器上附着的迭代器支持可选的`return`和`throw`方法，这两种方法都有立即终止一个暂停的生成器的效果

```js
function *foo() {
    yield 1
    yield 2
    yield 3
}
const it = foo()
console.log(it.next()) // { value: 1, done: false }
console.log(it.return(111)) // { value: 111, done: true }
console.log(it.next()) // { value: undefined, done: true }
```

可以finally子句执行清理任务

```js
function *foo() {
    try {
      yield 1
      yield 2
      yield 3
    } finally {
			console.log('cleanup!')
	}
}
const it = foo()
console.log(it.return(111))
// cleanup!
// { value: 111, done: true }
```

可以使用`throw`提前终止，和`return`不一样的是，`return`相当于`return x`而`throw`相当于`throw x`

```js
function *foo() {
	yield 1
	yield 2
	yield 3
}
const it = foo()
console.log(it.next()) // { value: 1, done: false }
console.log(it.throw(111)) // Uncaught 111
console.log(it.next()) // 永远不会执行
```

可以通过`catch`子句处理异常

```js
function *foo() {
  try {
		yield 1
		yield 2
		yield 3
  } catch (e) {
		console.log('cleanup!', e)
	}
}
const it = foo()
it.next()
console.log(it.throw(111))
```



### 3.2.5Transpile

模拟一个生成器的实现

```js
function foo () {
   let step = 0
   
   function next (v) {
      let res = undefined
      let done = true
      
      switch (step) {
            case 0:
               res = 42
            done = false
                break
            case 1:
               break
      }
      
      console.log(v)
      
      step++
        
        return {
         value: res,
            done
        }
    }
   
   return {
      next (v) {
         return next(v)
        }
    }
}

const it = foo()
console.log(it.next()) // { value: 42, done: false }
console.log(it.next(10)) // { value: undefined, done: true }
console.log(it.next()) // { value: undefined, done: true }
```

